/* ============================================================
   ReQuora — photo upload middleware (multer)
   Safety rules:
     - only jpg / png / webp / gif, up to 5 MB, one file
     - the stored file name is generated by the server (the original
       name is never used, so it cannot contain paths or scripts)
     - the file's real content is checked after upload; fakes are deleted
   ============================================================ */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const multer = require('multer');
const { LIMITS } = require('./constants');
const { Errors } = require('./http');
const { UPLOAD_DIR, detectImageTypeOfFile, removeFileIfExists } = require('./imageFiles');

const ALLOWED = {
  '.jpg': ['image/jpeg'],
  '.jpeg': ['image/jpeg'],
  '.png': ['image/png'],
  '.webp': ['image/webp'],
  '.gif': ['image/gif'],
};

const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    fs.mkdirSync(UPLOAD_DIR, { recursive: true });
    cb(null, UPLOAD_DIR);
  },
  filename: (req, file, cb) => {
    const ext = path.extname(file.originalname).toLowerCase();
    cb(null, `${Date.now()}-${crypto.randomUUID()}${ext}`);
  },
});

const upload = multer({
  storage,
  limits: { fileSize: LIMITS.imageBytes, files: 1 },
  fileFilter: (req, file, cb) => {
    const ext = path.extname(file.originalname).toLowerCase();
    const okType = ALLOWED[ext] && ALLOWED[ext].includes(String(file.mimetype).toLowerCase());
    if (okType) return cb(null, true);
    const err = new Error('Only photo files are allowed (JPG, PNG, WEBP or GIF).');
    err.code = 'INVALID_FILE_TYPE';
    return cb(err);
  },
});

// Accepts one optional photo in the "image" field.
const singleImage = upload.single('image');

// After multer has stored the file, confirm its content really is an image.
function verifyUploadedImage(req, res, next) {
  if (!req.file) return next();
  const detected = detectImageTypeOfFile(req.file.path);
  if (!detected) {
    removeFileIfExists(req.file.path);
    req.file = undefined;
    return next(Errors.validation('That file is not a valid photo. Please upload a JPG, PNG, WEBP or GIF image.', { image: 'Not a valid image file.' }));
  }
  return next();
}

// Removes the stored photo if the request later fails, so rejected reports
// never leave orphaned files behind. Use as the LAST step of the error path.
function cleanupUploadOnError(err, req, res, next) {
  if (req.file) removeFileIfExists(req.file.path);
  next(err);
}

module.exports = { singleImage, verifyUploadedImage, cleanupUploadOnError };
